GET http://localhost:3002/tasks

###

GET http://localhost:3002/tasks/:id

### 

DELETE http://localhost:3002/tasks/:id

###


POST http://localhost:3002/tasks
Content-Type: application/json

{
    "name": "Create APIs",
    "status": "finished"
    
}

###

PATCH http://localhost:3002/tasks/:id
Content-Type: application/json

{
    "name": "Update APIs",
    "status": "false"
}

###

POST http://localhost:3002/users
Content-Type: application/json

{
    "username": "herve",
    "password": "jesus123"
}

###

GET http://localhost:3002/users

###

PATCH http://localhost:3002/users/5e96acd6079f3a21ba8fd1da
Content-Type: application/json

{
    "username": "fidele",
    "password": "herve123"
}