GET http://localhost:3000/tasks

###

GET http://localhost:3000/tasks/:id

###

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "creator_id": "1",
    "name": "Create APIs",
    "status": "true"
    
}